@startuml
left to right direction

actor BA as "Business analyst"
rectangle Database

rectangle "HR System" {
    usecase UC1 as "Languages Used Report"
    usecase UC2 as "City Report"
    usecase UC3 as "Capital City Report"
    usecase UC4 as "Population Report"
    usecase UC5 as "Country Report"

    usecase UCp as "Print report"

     BA - UC1
     BA - UC2
     BA - UC3
     BA - UC4
     BA - UC5
    UC1 ..> UCp : include
    UC2 ..> UCp : include
    UC3 ..> UCp : include
    UC4 ..> UCp : include
    UC5 ..> UCp : include
    UC1 - Database
    UC2 - Database
    UC3 - Database
    UC4 - Database
    UC5 - Database
}
@enduml